### ISSUE TITLE
Removed XP support ?

### ISSUE THREAD

**Issue by devwhatsapp** [nsmfoo/antivmdetection#20]
Hi

Why was XP support removed ?

I would like to run this on XP. Please.

Thanks

**Comment by nsmfoo** [comment]
It was removed because the demand has not been that huge. After the removal, I think you are the first to ask for it to be supported again.  

That being said, you could probably get it to work by using and older version (0.1.4): https://github.com/nsmfoo/antivmdetection/commit/918f9c52ef17e714df4c67dede6f31d4c057752e 
Use the shell script from that version to apply to the VM and then you can use the current PS1 script inside of the host.

I can add XP support to my todo list, but no promise of it being re-introduced. If you fancy you are of course more then welcome to send me a PR for it

**Comment by nsmfoo** [comment]
If I get the time to re-implement XP support, I will re-open this case. But feel free to jump ahead and send me a PR =)
