### ISSUE TITLE
Feature: Run this where host is MacOS

### ISSUE THREAD

**Issue by escugs** [nsmfoo/antivmdetection#21]
Hello,

Nice script that you made.
Biggest problem i have its i am running VirtalBox on my mac. I did make changes my self manaul. 

I hope you can make one that run on MacOS too.

**Comment by nsmfoo** [comment]
Hi, So sorry for my late reply!

The problem running on a Mac, is that it does not expose all the values that you would like to use to populate your Windows guest. I did make some changes so that the script does not crash on mac, but for a better experience I recommend that you boot a random non-mac computer with a live-cd and run the script on that system. You can then use the template on your mac

**Comment by nsmfoo** [comment]
I will close this one, but feel free to open it again if you like =)
