### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by crunchor** [nsmfoo/antivmdetection#27]
Hi everyone I am new to to this and this is what I try:
1. Setup a new Virtualbox VM with IDE: Primary master (Disk) and Primary slave (CD-ROM) + SATA: Port 0 (Disk) and Port 1 (CD-ROM)
2. Install Windows 7 in the VM
3. Install latest Python 2.7 in Win 7
4. Run the  antivmdetection py
Do I miss any important step? Thanks.

**Comment by capsudo** [comment]
- install dependencies `apt-get install python-dmidecode libcdio-utils acpidump mesa-utils`
- download win binaries and extract them in antivmdetection directory : `wget https://download.sysinternals.com/files/VolumeId.zip  https://www.nirsoft.net/utils/devmanview-x64.zip` for 64bits.
- run python script as sudo `sudo python antivmdetection.py`
- make generated host script executable from current user `sudo chmod a+x xxxxx.sh`
- run script as current user (because VMs are located in current user home dir) : `/bin/bash xxxxx.sh my-virtual-machine-name`
- install OS on VM
- run powershell script inside VM : double click xxxx.ps1

**Comment by lironexex** [comment]
How do I use this on windows 10? I don't have the command "apt-get install"

**Comment by nsmfoo** [comment]
@crunchor the response that @monkeydri gave was spot on, I hoped it helped you get started. If not please let me know

**Comment by nsmfoo** [comment]
@lironexex it's often best to start a new issue, but to answer your question. The script will only work on Linux and MacOS, but can be applied to a Windows 7/10 VM guest running on these OS:es. I hope this answers your question. If not or if you have more questions please open a issue and I will try to help you out.

**Comment by Zefest** [comment]
After run .sh script : 
" VBoxManage: error: Could not find a registered machine named 'z1' "

Can you halp me with dir? Where mast be locations virtualbox, and where script .sh?

**Comment by nsmfoo** [comment]
@Zefest as you jumped into a already open case, I missed you question. Best is to open a new one.
Anyway, the user that you are trying to run the script as, it that user member of the vbox group? Most likely not.  Review the following: https://www.virtualbox.org/manual/ch08.html#vboxmanage-list
