### ISSUE TITLE
KeyError: 'Relase Date'

### ISSUE THREAD

**Issue by WanpengQian** [nsmfoo/antivmdetection#5]
```
--- Generate VirtualBox templates to help thwart vm detection - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
Traceback (most recent call last):
  File "./antivmdetect.py", line 38, in <module>
    dmi_info['DmiBIOSReleaseDate'] = v['data']['Relase Date']
KeyError: 'Relase Date'
```

type mistake?

**Comment by nsmfoo** [comment]
Can you include the full output of dmidecode.bios().values() (or the output from dmidecode -t 0)?

**Comment by WanpengQian** [comment]
here is the output

```
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 2.7 present.

Handle 0x000A, DMI type 0, 24 bytes
BIOS Information
    Vendor: Dell Inc.
    Version: 2.8.0
    Release Date: 06/24/2014
    Address: 0xF0000
    Runtime Size: 64 kB
    ROM Size: 4096 kB
    Characteristics:
        ISA is supported
        PCI is supported
        PNP is supported
        BIOS is upgradeable
        BIOS shadowing is allowed
        Boot from CD is supported
        Selectable boot is supported
        EDD is supported
        Japanese floppy for Toshiba 1.2 MB is supported (int 13h)
        5.25"/360 kB floppy services are supported (int 13h)
        5.25"/1.2 MB floppy services are supported (int 13h)
        3.5"/720 kB floppy services are supported (int 13h)
        8042 keyboard services are supported (int 9h)
        Serial services are supported (int 14h)
        CGA/mono video services are supported (int 10h)
        ACPI is supported
        USB legacy is supported
        BIOS boot specification is supported
        Function key-initiated network boot is supported
        Targeted content distribution is supported
        UEFI is supported
    BIOS Revision: 2.8

```

I change `Relase Date` to `Release Date`, and works.

**Comment by nsmfoo** [comment]
Can you send me another output? If possible can you add "print v"  below "for v in dmidecode.bios().values():"

It might be an issue with the version of python-dmidecode that I'm using as it contains the misspelled variable (Relase Date), it might also have been fixed. I will add try to add a check for both conditions

**Comment by WanpengQian** [comment]
Here is the output(after adding print v, also change `Relase Date` to`Release Date`)

```
--- Generate VirtualBox templates to help thwart vm detection - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
{'dmi_type': 13, 'data': {'Currently Installed Language': ['en|US|iso8859-1'], 'Installed Languages': 1}, 'dmi_handle': '0x0026', 'dmi_size': 22}
{'dmi_type': 0, 'data': {'Vendor': 'Dell Inc.', 'Characteristics': {'NEC PC-98': False, 'EDD is supported': True, 'PC Card (PCMCIA) is supported': False, '3.5"/2.88 MB floppy services are supported (int 13h)': False, '5.25"/360 kB floppy services are supported (int 13h)': True, 'Printer services are supported (int 17h)': False, 'BIOS is upgradeable': True, '8042 keyboard services are supported (int 9h)': True, 'BIOS shadowing is allowed': True, 'BIOS ROM is socketed': False, 'APM is supported': False, 'PNP is supported': True, 'VLB is supported': False, 'ISA is supported': True, 'Japanese floppy for Toshiba 1.2 MB is supported (int 13h)': True, 'CGA/mono video services are supported (int 10h)': True, 'Serial services are supported (int 14h)': True, '3.5"/720 kB floppy services are supported (int 13h)': True, 'MCA is supported': False, 'PCI is supported': True, '5.25"/1.2 MB floppy services are supported (int 13h)': True, 'Selectable boot is supported': True, 'Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)': False, 'EISA is supported': False, 'Boot from PC Card (PCMCIA) is supported': False, 'ESCD support is available': False, 'Boot from CD is supported': True, 'Print screen service is supported (int 5h)': False}, 'Runtime Size': '64 KB', 'BIOS Revision': '2.8', 'Version': '2.8.0', 'ROM Size': '4096 KB', 'Characteristic x2': {'System is a virtual machine': False, 'UEFI is supported': False, 'Targeted content distribution': False, 'Function key-initiated network boot': True, 'BIOS boot specification': True}, 'Address': '0xf0000', 'Release Date': '06/24/2014', 'Characteristic x1': {'I2O boot': False, 'USB legacy': True, 'ATAPI Zip drive boot': False, 'Smart battery': False, 'IEEE 1394 boot': False, 'ACPI': True, 'LS-120 boot': False, 'AGP': False}}, 'dmi_handle': '0x000a', 'dmi_size': 24}
[*] Creating a DSDT file...
[*] Finished: A template shell script has been created named: PowerEdgeT110II.sh
[*] Finished: A DSDT dump has been created named: DSDT_PowerEdgeT110II.bin
[*] Creating guest based modification file (to be run inside the guest)...
[*] Finished: A Windows batch file has been created named: PowerEdgeT110II.bat
```

**Comment by nsmfoo** [comment]
Thank you for the information!

The thing is that the misspelled "Relase Date" is fixed in python-dmidecode, 3.12.2-2. Which is the version shipped with Ubuntu 16.04. The version included in Ubuntu 14.04 still have the misspelled item.

Are you able to verify if the latest commits resolves your issue?

**Comment by nsmfoo** [comment]
Due to the lack of feedback, I will close this issue.But please feel free to re-open if the problem still persist

**Comment by ShonInDim** [comment]
Hello Mikael ! 
My problem is similar, i have install all dependencies python-dmidecode3.12.2-2 and others. 
After that the output is : 
``--- Generate VirtualBox templates to help thwart vm detection - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
Traceback (most recent call last):
  File "antivmdetect.py", line 38, in <module>
    dmi_info['DmiBIOSReleaseDate'] = v['data']['Relase Date']
KeyError: 'Relase Date'

So I add print into antivmdetect.py :
 `--- Generate VirtualBox templates to help thwart vm detection - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
{'dmi_type': 0, 'data': {'Vendor': 'American Megatrends Inc.', 'Characteristics': {'NEC PC-98': False, 'EDD is supported': True, 'PC Card (PCMCIA) is supported': False, '3.5"/2.88 MB floppy services are supported (int 13h)': True, '5.25"/360 kB floppy services are supported (int 13h)': False, 'Printer services are supported (int 17h)': True, 'BIOS is upgradeable': True, '8042 keyboard services are supported (int 9h)': True, 'BIOS shadowing is allowed': True, 'BIOS ROM is socketed': True, 'APM is supported': False, 'PNP is supported': False, 'VLB is supported': False, 'ISA is supported': False, 'Japanese floppy for Toshiba 1.2 MB is supported (int 13h)': False, 'CGA/mono video services are supported (int 10h)': False, 'Serial services are supported (int 14h)': True, '3.5"/720 kB floppy services are supported (int 13h)': True, 'MCA is supported': False, 'PCI is supported': True, '5.25"/1.2 MB floppy services are supported (int 13h)': True, 'Selectable boot is supported': True, 'Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)': False, 'EISA is supported': False, 'Boot from PC Card (PCMCIA) is supported': False, 'ESCD support is available': False, 'Boot from CD is supported': True, 'Print screen service is supported (int 5h)': True}, 'Runtime Size': '64 KB', 'BIOS Revision': '4.6', 'Version': '211', 'ROM Size': '1024 KB', 'Characteristic x2': {'System is a virtual machine': False, 'UEFI is supported': False, 'Targeted content distribution': False, 'Function key-initiated network boot': True, 'BIOS boot specification': True}, 'Address': '0xf0000', 'Release Date': '07/14/2014', 'Characteristic x1': {'I2O boot': False, 'USB legacy': True, 'ATAPI Zip drive boot': False, 'Smart battery': False, 'IEEE 1394 boot': False, 'ACPI': True, 'LS-120 boot': False, 'AGP': False}}, 'dmi_handle': '0x0000', 'dmi_size': 24}
Traceback (most recent call last):
  File "antivmdetect.py", line 39, in <module>
    dmi_info['DmiBIOSReleaseDate'] = v['data']['Relase Date']
KeyError: 'Relase Date'`
Could you give me advice to resolve this problem ?
thank you in advance.
By the way, actually not so long time ago, I already try to ran this script so that time the output : some about DSDT larger than 64K etc  ... after that I made some dump from another device.
So, this time I have problem from my BIOS ?
