### ISSUE TITLE
"relase" on line 50 and suggestions

### ISSUE THREAD

**Issue by looi-wh** [nsmfoo/antivmdetection#57]
you miswrote "release" as "relase" on line 50. I corrected it and the script got working again.

and i suggest you to change your readme.md on one of its line:
pip3 -r requirements.txt
to
sudo pip3 -r requirements.txt

as running it without superuser caused dmidecode not to be found in modules

**Comment by nsmfoo** [comment]
Hi @looi-wh , 

thank you for your contribution!

* Regarding "relase" spelling, it's actually by design, albit a bit funny. The reason for it was because at some point python-dmidecode contained that misspelling. Hence I needed to catch that as well

* Regarding the "sudo" things, there is a PR, which I will review shortly

/Mikael

**Comment by nsmfoo** [comment]
PR approved and a comment added to the code, that will make the reason why the typo exist is in the code more clear.
Thank you for your feedback!
